# Generated by Django 5.0.14 on 2026-07-25 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('visualization_type', models.CharField(choices=[('LINE_CHART', 'Line Chart'), ('BAR_CHART', 'Bar Chart'), ('SCATTER_PLOT', 'Scatter Plot'), ('HISTOGRAM', 'Histogram'), ('HEATMAP', 'Heatmap'), ('GEOGRAPHIC_MAP', 'Geographic Map'), ('CHOROPLETH_MAP', 'Choropleth Map'), ('TABLE', 'Table (fallback)'), ('SCENE_3D', '3D Scene')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('x_axis', models.JSONField(blank=True, null=True)),
                ('y_axis', models.JSONField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualization_configs', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
