# Generated by Django 5.0.14 on 2026-07-25 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('missing_values_report', models.JSONField(blank=True, default=dict)),
                ('duplicate_row_count', models.PositiveIntegerField(default=0)),
                ('correlation_matrix', models.JSONField(blank=True, null=True)),
                ('analyzer_version', models.CharField(default='structured-v1', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=255)),
                ('detected_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('CATEGORICAL', 'Categorical'), ('DATETIME', 'Datetime'), ('BOOLEAN', 'Boolean'), ('LATITUDE', 'Latitude'), ('LONGITUDE', 'Longitude'), ('IDENTIFIER', 'Identifier'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('missing_pct', models.FloatField(default=0.0)),
                ('unique_count', models.PositiveIntegerField(default=0)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('dataset_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_profiles', to='analysis.datasetprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
