# Generated by Django 5.0.14 on 2026-07-25 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('engine_used', models.CharField(choices=[('RULE_BASED', 'Rule-based'), ('AI', 'AI (LLM-backed)')], max_length=20)),
                ('matched_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('recommended_type', models.CharField(choices=[('LINE_CHART', 'Line Chart'), ('BAR_CHART', 'Bar Chart'), ('SCATTER_PLOT', 'Scatter Plot'), ('HISTOGRAM', 'Histogram'), ('HEATMAP', 'Heatmap'), ('GEOGRAPHIC_MAP', 'Geographic Map'), ('CHOROPLETH_MAP', 'Choropleth Map'), ('TABLE', 'Table (fallback)'), ('SCENE_3D', '3D Scene')], max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='datasets.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
